givenchy_eyelip_homepage:
    path:     /index
    defaults: { _controller: GivenchyEyelipBundle:Page:index }

givenchy_eyelip_photolist:
    path:     /photolist
    defaults: { _controller: GivenchyEyelipBundle:Page:photolist }

givenchy_eyelip_upload:
    path:     /upload
    defaults: { _controller: GivenchyEyelipBundle:Page:upload }

givenchy_eyelip_result:
    path:     /result
    defaults: { _controller: GivenchyEyelipBundle:Page:result }

givenchy_eyelip_info:
    path:     /info
    defaults: { _controller: GivenchyEyelipBundle:Page:info }

givenchy_eyelip_finish:
    path:     /finish
    defaults: { _controller: GivenchyEyelipBundle:Page:finish }

givenchy_eyelip_check:
    path:     /check
    defaults: { _controller: GivenchyEyelipBundle:Page:check }

givenchy_eyelip_user:
    path:     /user
    defaults: { _controller: GivenchyEyelipBundle:Page:user }

givenchy_eyelip_lottery:
    path:     /lottery
    defaults: { _controller: GivenchyEyelipBundle:Page:lottery }

givenchy_eyelip_test:
    path:     /test
    defaults: { _controller: GivenchyEyelipBundle:Default:test }

givenchy_eyelip_api_test:
    path:     /api/islogin
    defaults: { _controller: GivenchyEyelipBundle:Api:islogin }

givenchy_eyelip_api_upload:
    path:     /api/upload
    defaults: { _controller: GivenchyEyelipBundle:Api:upload }

givenchy_eyelip_api_getvideo:
    path:     /api/getvideo/id/{id}
    defaults: { _controller: GivenchyEyelipBundle:Api:getvideo }

givenchy_eyelip_api_check:
    path:     /api/check
    defaults: { _controller: GivenchyEyelipBundle:Api:check }

givenchy_eyelip_api_ballot:
    path:     /api/ballot/id/{id}
    defaults: { _controller: GivenchyEyelipBundle:Api:ballot }

