services:
   givenchy.image.service:
       class: Givenchy\EyelipBundle\Services\Image\ImageService
       arguments: [@service_container]

   givenchy.user.service:
        class: Givenchy\EyelipBundle\Services\User\UserService
        arguments: [@doctrine.orm.entity_manager, @request_stack]